config/routes.rb
Rails.application.routes.draw do
  delete  'admin', to: 'session#logout'

  namespace :admin do
    resources :media_categories
    resources :media
    resources :question_categories
    resources :title_questions
    resources :questions
    resources :members
    resources :histories

    root to: 'questions#index'
  end

  constraints format: :json do
    post  '/login',                         to: 'members#sign_in'
    get   '/logout',                        to: 'members#sign_out'
    post  '/users',                         to: 'members#sign_up'
    get   '/forgot_password',               to: 'members#forgot_password'
    get   '/users/:user_id',                to: 'members#profile'
    put   '/users/:user_id',                to: 'members#update_profile'
    put   '/users/:user_id/password',       to: 'members#change_password'

    post  '/photos',                        to: 'images#upload'

    get   '/media',                         to: 'media#index'

    get   '/questions',                     to: 'questions#index'

    post  '/users/:user_id/answers',        to: 'histories#create'
    get   '/users/:user_id/answers',        to: 'histories#index'
    get   '/users/:user_id/answers/:id',    to: 'histories#show'
  end

  get 'file/:type/*path',                   to: 'files#show'
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :parent, class_name: 'TitleQuestion', foreign_key: 'parent_id', optional: true

  default_scope { order(:category, :is_sample, :sequence) }
  scope :category, -> (category) { where(category: category) }
  scope :sample?, -> (is_sample) { where(is_sample: is_sample) }

  scope :level, -> (level) { select { |question| question.data.include?(level) } }

  def as_json(*)
    {
      id: id,
      title: title,
      order: sequence,
      data: data,
      parent_id: parent_id
    }
  end

  def self.as_json(questions)
    list = questions.group_by { |question| question['parent_id'] }

    list.map do |parent_id, question_list|
      {
        titles: titles(TitleQuestion.find(parent_id)),
        questions: question_list.as_json
      }
    end
  end

  def self.titles(parent, list = [])
    return list.reverse if parent.nil?

    list << parent.title

    titles(parent.parent, list)
  end
end

app/controllers/admin/questions_controller.rb
module Admin
  class QuestionsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Question.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Question.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.category(params[:type]).sample?(current_member.nil?)

    render json: Question.as_json(@questions), status: :ok
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :is_sample %>
    <%= form.text_field :is_sample %>
  </div>

  <div class="field">
    <%= form.label :data %>
    <%= form.text_field :data %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Category</th>
      <th>Is sample</th>
      <th>Data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.title %></td>
        <td><%= question.category %></td>
        <td><%= question.is_sample %></td>
        <td><%= question.data %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @question.title %>
</p>

<p>
  <strong>Category:</strong>
  <%= @question.category %>
</p>

<p>
  <strong>Is sample:</strong>
  <%= @question.is_sample %>
</p>

<p>
  <strong>Data:</strong>
  <%= @question.data %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>