config/routes.rb
Rails.application.routes.draw do
  delete  'admin', to: 'session#logout'

  namespace :admin do
    resources :media_categories
    resources :media
    resources :question_categories
    resources :title_questions
    resources :questions
    resources :members
    resources :histories

    root to: 'questions#index'
  end

  constraints format: :json do
    post  '/login',                         to: 'members#sign_in'
    get   '/logout',                        to: 'members#sign_out'
    post  '/users',                         to: 'members#sign_up'
    get   '/forgot_password',               to: 'members#forgot_password'
    get   '/users/:user_id',                to: 'members#profile'
    put   '/users/:user_id',                to: 'members#update_profile'
    put   '/users/:user_id/password',       to: 'members#change_password'

    post  '/photos',                        to: 'images#upload'

    get   '/media',                         to: 'media#index'

    get   '/questions',                     to: 'questions#index'

    post  '/users/:user_id/answers',        to: 'histories#create'
    get   '/users/:user_id/answers',        to: 'histories#index'
    get   '/users/:user_id/answers/:id',    to: 'histories#show'
  end

  get 'file/:type/*path',                   to: 'files#show'
end

app/models/member.rb
class Member < ApplicationRecord
  default_scope { order(:created_at) }

  has_many :devices
  has_many :histories

  validate :validate_citizen_id
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates_presence_of :email
  validates_uniqueness_of :email
  validates :password, length: { minimum: 6 }

  after_create :update_tosh_id

  mount_uploader :avatar, ImageUploader

  def as_json(options = nil)
    {
      id: id,
      tosh_id: tosh_id,
      title: title,
      first_name: firstname,
      last_name: lastname,
      phone_number: phone,
      id_card_number: citizen_id,
      email: email,
      photo_url: avatar_url(options)
    }
  end

  private

  def validate_citizen_id
    errors.add(:citizen_id, "invalid citizen id") unless CitizenIdValidate.new(citizen_id)
  end

  def avatar_url(options)
    avatar.url || photo_url(options)
  end

  def photo_url(options)
    return if options.nil?

    options[:photo_url]
  end

  def update_tosh_id
    zeros = '0' * (6 - id.to_s.size)
    year = (Date.today.year + 543).to_s.last(2)

    update!(tosh_id: "tosh#{year}#{zeros}#{id}")
  end
end

app/controllers/admin/members_controller.rb
module Admin
  class MembersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Member.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Member.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  def sign_in
    @member = Member.find_by(
      email: params[:email],
      password: params[:password]
    )

    respond_to do |format|
      if @member.present?
        device = @member.devices.create!(token: SecureRandom.uuid)

        format.json { render json: device.as_json, status: :ok }
      else
        format.json { render json: { message: "Invalid email or password" }, status: :bad_request }
      end
    end
  end

  def sign_out
    device = Device.find_by(token: authorization_token)

    if device.present?
      device.destroy!

      render json: device, status: :ok
    else
      render json: { message: "device not found" }, status: :bad_request
    end
  end

  def sign_up
    return render json: { message: 'email is already taken' }, status: :bad_request if Member.find_by_email(params[:email]).present?

    @member = Member.new(member_params)

    if @member.save
      device = @member.devices.create!(token: SecureRandom.uuid)

      render json: device.as_json, status: :created
    else
      render json: { message: { @member.errors.first[0] => [@member.errors.first[1]] }.to_s }, status: :bad_request
    end
  end

  def forgot_password
    @member = Member.find_by(email: params[:email])

    if @member.present?
      MemberMailer.forgot_password(@member).deliver_now

      render json: @member.as_json, status: :created
    else
      render json: { message: "member not found" }, status: :bad_request
    end
  end

  def profile
    @member = current_member

    if @member.present?
      render json: @member.as_json, status: :created
    else
      render json: { message: "member not found" }, status: :bad_request
    end
  end

  def update_profile
    @member = current_member
    member = Member.find_by_email(params[:email])
    return render json: { message: 'email is already taken' }, status: :bad_request if member.present? && member != @member

    if @member.present? && @member.update(member_params)
      render json: @member.as_json(params), status: :created
    else
      render json: { message: @member.present? ? { @member.errors.first[0] => [@member.errors.first[1]] }.to_s : "member not found" }, status: :bad_request
    end
  end

  def change_password
    @member = current_member

    if @member.present? && @member.password == params[:old_password] && @member.update(password: params[:new_password])
      render json: @member.as_json, status: :created
    else
      render json: { message: @member.present? ? { @member.errors.first[0] => [@member.errors.first[1]] }.to_s : "member not found" }, status: :bad_request
    end
  end

  private

  def member_params
    params.permit(:title, :first_name, :last_name, :phone_number, :id_card_number, :email, :password, :photo_url)

    p = {}
    p.merge!(title: params[:title]) if params[:title].present?
    p.merge!(firstname: params[:first_name]) if params[:first_name].present?
    p.merge!(lastname: params[:last_name]) if params[:last_name].present?
    p.merge!(phone: params[:phone_number]) if params[:phone_number].present?
    p.merge!(citizen_id: params[:id_card_number]) if params[:id_card_number].present?
    p.merge!(email: params[:email]) if params[:email].present?
    p.merge!(password: params[:password]) if params[:password].present?
    p.merge!(remote_avatar_url: params[:photo_url]) if params[:photo_url].present?

    p
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_with(model: member, local: true) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :firstname %>
    <%= form.text_field :firstname %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :citizen_id %>
    <%= form.text_field :citizen_id %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="field">
    <%= form.label :avatar %>
    <%= form.text_field :avatar %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Members</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Phone</th>
      <th>Citizen</th>
      <th>Email</th>
      <th>Password</th>
      <th>Avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.firstname %></td>
        <td><%= member.lastname %></td>
        <td><%= member.phone %></td>
        <td><%= member.citizen_id %></td>
        <td><%= member.email %></td>
        <td><%= member.password %></td>
        <td><%= member.avatar %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @member.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @member.lastname %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @member.phone %>
</p>

<p>
  <strong>Citizen:</strong>
  <%= @member.citizen_id %>
</p>

<p>
  <strong>Email:</strong>
  <%= @member.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @member.password %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @member.avatar %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>